# Generated by Django 5.0.6 on 2024-07-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='url',
            field=models.SlugField(blank=True),
        ),
    ]
