# Generated by Django 5.0.6 on 2024-07-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0002_lessons_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='answer_les',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessons',
            name='text_les',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
