# Generated by Django 5.0.6 on 2024-07-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0004_taglessons_alter_lessons_url_lessons_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('time_send', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Lessons',
        ),
        migrations.DeleteModel(
            name='TagLessons',
        ),
    ]
